### PR TITLE
Static Drag Fix

### LINKED ISSUE #2: Can drag elements over static end cards
You can move orange cards to left and right of purple ones.

This means that you can drag things before the "0" card and after the "1" card. This should not be allowed.

### PR DESCRIPTION
**Pull request by bxs9775**
* end cards have been moved out of the ordered list so you cannot drag past them.
* Error: can't drag into the rightmost spot
* Error: the "1" card is a few pixels down, not aligned with the other cards

### CODE REVIEW

**Comment by solanin** [comment]
Why are there 700+ file changes?

**Comment by solanin** [comment]
Wait is this a full fix or a partial? On Hangouts I thought you said this was only a partial fix?

**Comment by solanin** [comment]
I cannot see your changes for the fix clearly though all the files here

**Comment by bxs9775** [comment]
Sorry I didn't see your comments earlier. I don't know why all those changes show up. They were committed in when I branched. It fixed the issue of drag, but it messes up the styling a bit. Some I didn't realize until after I made the request. And it doesn't deal with the last item problem.

**Comment by solanin** [comment]
Okay well, since that issue is now resolved in the master branch lets figure out what all the file changes are before proceeding.

I didnt see any branches you made, could you have pulled in from the wrong spot or something?

**Comment by bxs9775** [comment]
I pushed from bxs9775/Sugarizer branch Solanin to Fractionators/Sugarizer
branch Solanin.

**Comment by solanin** [comment]
Ok, did you install your own sugar package? When did you fork the project?

**Comment by bxs9775** [comment]
Has this been pulled into the main repo?

**Comment by bxs9775** [comment]
Also, I took out the fixes issue line just now.

**Pull request closed without merging**
